### ISSUE TITLE
Populate docs with continues delivery based on Travis + GitHub

### ISSUE THREAD

**Issue by ikalnytskyi** [ikalnytskyi/holocron#187]
If one wants to publish its site on GitHub (i.e. GitHub Pages) there's a way to do this automatically by means of Travis CI. We should provide working example in our docs as most easies and recommended way.

**Comment by webknjaz** [comment]
Travis CI is no more these days. Years ago, I wrote the first implementation of their integration with GH Pages (https://github.com/travis-ci/dpl/commit/58f6c7dd4f0fd49df2e93a8495fd01c7784d4f58) so it's interesting to see that still being mentioned. Nowadays, it's rather straightforward to publish via GHA: https://github.com/webknjaz/intersphinx-untangled/blob/5eeb7ec/.github/workflows/build-gh-pages.yml#L85-L110.

Though, I'd suggest looking into plugging RTD, where you can also host any static website nowadays, since the configuration is much more flexible nowadays:

- https://github.com/ansible/awx/blob/587f0ec/.readthedocs.yaml
- https://github.com/ansible/docsite/blob/3ae5a22/.readthedocs.yaml
- https://github.com/ansible/jinja-docsite/blob/00290a6/.readthedocs.yaml
- https://github.com/ansible/ansible-documentation/blob/780b4d9/.readthedocs.yaml

**Comment by ikalnytskyi** [comment]
@webknjaz Oh my... you just dug up a 7-year-old ticket :smile: I long lost hope of making this pet project into something usable, although I still use it to build my static site.

Thank you very much for sharing some links. I wasn't aware that there's finally an official `actions/deploy-pages` action to publish the site. I'm gonna switch to it immediately. :)
